### ISSUE TITLE
￼\bibliographystyle{unsrt} raises flap.engine.ResourceNotFound: None

### ISSUE THREAD

**Issue by Ohjeah** [fchauvel/flap#20]
```text
control.tex                       99      1 \bibliographystyle{unsrt}          
Traceback (most recent call last):
  File "/home/mq/miniconda3/bin/flap", line 9, in <module>
    load_entry_point('FLaP', 'console_scripts', 'flap')()
  File "/home/mq/repo/github/flap/flap/ui.py", line 106, in main
    Controller(OSFileSystem(), Display(sys.stdout)).run(arguments)
  File "/home/mq/repo/github/flap/flap/ui.py", line 38, in run
    request.execute()
  File "/home/mq/repo/github/flap/flap/engine.py", line 69, in execute
    flattened = self._rewrite(self.read_root_tex, str(self.root_tex_file.resource()))
  File "/home/mq/repo/github/flap/flap/engine.py", line 76, in _rewrite
    return parser.rewrite()
  File "/home/mq/repo/github/flap/flap/latex/parser.py", line 100, in rewrite
    result += self._rewrite_one()
  File "/home/mq/repo/github/flap/flap/latex/parser.py", line 108, in _rewrite_one
    return self._evaluate_one()
  File "/home/mq/repo/github/flap/flap/latex/parser.py", line 156, in _evaluate_one
    return self.evaluate_command(str(self._next_token))
  File "/home/mq/repo/github/flap/flap/latex/parser.py", line 181, in evaluate_command
    return macro.invoke(self)
  File "/home/mq/repo/github/flap/flap/latex/macros.py", line 111, in invoke
    return self._execute(parser, invocation)
  File "/home/mq/repo/github/flap/flap/latex/macros.py", line 357, in _execute
    new_link = self.update_link(parser, link, invocation)
  File "/home/mq/repo/github/flap/flap/latex/macros.py", line 397, in update_link
    return parser._engine.update_link_to_bibliography_style(link, invocation)
  File "/home/mq/repo/github/flap/flap/engine.py", line 111, in update_link_to_bibliography_style
    return self._update_link(path, invocation, [self.root_directory], ["bst"], ResourceNotFound(None))
  File "/home/mq/repo/github/flap/flap/engine.py", line 119, in _update_link
    resource = self._find(path, location, extensions, error)
  File "/home/mq/repo/github/flap/flap/engine.py", line 151, in _find
    raise error
flap.engine.ResourceNotFound: None
```

**Comment by fchauvel** [comment]
This was easy to fix. Feel free to reopen the issue if the problem remains.

**Comment by Ohjeah** [comment]
Thanks works like a charm now.
