### ISSUE TITLE
ValueError: Unexpected CONTROL '\MessageBreak' in file svjour3.cls (line 130, column 1).

### ISSUE THREAD

**Issue by suvojit-0x55aa** [fchauvel/flap#37]
Below is the whole log:

```shell
Traceback (most recent call last):
  File "/Users/shin/miniconda3/envs/latex_env/bin/flap", line 8, in <module>
    sys.exit(main())
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/ui.py", line 102, in main
    Controller(OSFileSystem(), Display(sys.stdout, verbose)).run(tex_file, output)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/ui.py", line 43, in run
    request.execute()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/engine.py", line 79, in execute
    flattened = self._rewrite(self.read_root_tex, str(self.root_tex_file.resource()))
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/engine.py", line 88, in _rewrite
    return parser.rewrite()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 78, in rewrite
    result += self._rewrite_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 86, in _rewrite_one
    return self._evaluate_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 138, in _evaluate_one
    return self.evaluate_command(str(self._next_token))
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 164, in evaluate_command
    return macro.invoke(self)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 124, in invoke
    return self._execute(parser, invocation)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 207, in _execute
    self._flap.relocate_dependency(class_name, invocation)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/engine.py", line 109, in relocate_dependency
    self._rewrite(file.content(), file.fullname(), symbol_table)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/engine.py", line 88, in _rewrite
    return parser.rewrite()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 78, in rewrite
    result += self._rewrite_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 86, in _rewrite_one
    return self._evaluate_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 138, in _evaluate_one
    return self.evaluate_command(str(self._next_token))
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 164, in evaluate_command
    return macro.invoke(self)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 123, in invoke
    invocation = self._parse(parser)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 129, in _parse
    self._capture_arguments(parser, invocation)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 144, in _capture_arguments
    value = parser._evaluate_until(lambda token: token.has_text(next_token._text))
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 153, in _evaluate_until
    tokens += self._evaluate_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 136, in _evaluate_one
    return self._evaluate_group()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 146, in _evaluate_group
    tokens = self._evaluate_until(lambda token: token.ends_a_group)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 153, in _evaluate_until
    tokens += self._evaluate_one()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 138, in _evaluate_one
    return self.evaluate_command(str(self._next_token))
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 164, in evaluate_command
    return macro.invoke(self)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 123, in invoke
    invocation = self._parse(parser)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 129, in _parse
    self._capture_arguments(parser, invocation)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/macros.py", line 203, in _capture_arguments
    invocation.append_argument("class", parser.capture_group())
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 203, in capture_group
    tokens = self._accept(lambda token: token.begins_a_group)
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 109, in _accept
    self._raise_unexpected_token()
  File "/Users/shin/miniconda3/envs/latex_env/lib/python3.6/site-packages/flap/latex/parser.py", line 118, in _raise_unexpected_token
    raise ValueError(error)
```

**Comment by fchauvel** [comment]
Thanks for the feedback. I will try to take a look later this week if time allows.  Note that I am not maintaining FLaP actively. I'll keep you posted.

**Comment by fchauvel** [comment]
Sorry for this late reply. Took me some time to refresh the FLaP project ;-)

I am not about to reproduce the crash you describe. Would you mind sharing more details about your LaTeX project?
